applications:
  test-project:
    type: "php:8.3"
    runtime:
      extensions:
        - pdo
        - pdo_mysql

    relationships:
      database: "mysql:mysql"
      
    web:
      locations:
        "/":
          passthru: "/index.php"
          root: ""
          
    hooks:
      build: |
        set -eux
        
        # Add build steps here.
        # echo 'I am a build step'
        
      deploy: |
        set -eux
        # echo 'Put your deploy command here'
        
services:
  mysql:
    type: mysql:10.6

routes:
  "https://{default}/":
    type: upstream
    upstream: "test-project:http"
