applications:
  test-project:
    stack: 
      - "php@8.3":
        extensions:
          - intl
          - zip
          - pdo_pgsql
          - pcntl
          - redis
      - "nodejs@22"

    relationships:
      database: "mysql:mysql"
      
    web:
      locations:
        "/":
          passthru: "/index.php"
          root: ""
          
    hooks:
      build: |
        set -eux
        
        # Add build steps here.
        # echo 'I am a build step'
        
      deploy: |
        set -eux
        # echo 'Put your deploy command here'
        
services:
  mysql:
    type: mysql:10.6

routes:
  "https://{default}/":
    type: upstream
    upstream: "test-project:http"
